
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.IronPython.Gui
{
	public partial class OptionsWidget
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.Label label1;
		private global::Gtk.Alignment alignment1;
		private global::Gtk.Table table1;
		private global::Gtk.Label label2;
		private global::Gtk.Label label3;
		private global::Gtk.Label label4;
		private global::Gtk.Entry moduleEntry;
		private global::Gtk.CheckButton optimizeCheck;
		private global::Gtk.Entry runtimeOptionsEntry;
		private global::Gtk.CheckButton showClrExcCheck;
		private global::Gtk.CheckButton showExcDetailCheck;
		private global::Gtk.ComboBox versionComboBox;
		private global::Gtk.CheckButton warnInconsistentTabCheck;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.IronPython.Gui.OptionsWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoDevelop.IronPython.Gui.OptionsWidget";
			// Container child MonoDevelop.IronPython.Gui.OptionsWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Runtime</b>");
			this.label1.UseMarkup = true;
			this.vbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.LeftPadding = ((uint)(12));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(7)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Python options:");
			this.table1.Add (this.label2);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Python version:");
			this.table1.Add (this.label3);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.label3]));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Default module:");
			this.table1.Add (this.label4);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.label4]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.moduleEntry = new global::Gtk.Entry ();
			this.moduleEntry.CanFocus = true;
			this.moduleEntry.Name = "moduleEntry";
			this.moduleEntry.IsEditable = true;
			this.moduleEntry.InvisibleChar = '•';
			this.table1.Add (this.moduleEntry);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.moduleEntry]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.optimizeCheck = new global::Gtk.CheckButton ();
			this.optimizeCheck.CanFocus = true;
			this.optimizeCheck.Name = "optimizeCheck";
			this.optimizeCheck.Label = global::Mono.Unix.Catalog.GetString ("Optimize");
			this.optimizeCheck.DrawIndicator = true;
			this.optimizeCheck.UseUnderline = true;
			this.table1.Add (this.optimizeCheck);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.optimizeCheck]));
			w6.TopAttach = ((uint)(3));
			w6.BottomAttach = ((uint)(4));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.runtimeOptionsEntry = new global::Gtk.Entry ();
			this.runtimeOptionsEntry.CanFocus = true;
			this.runtimeOptionsEntry.Name = "runtimeOptionsEntry";
			this.runtimeOptionsEntry.IsEditable = true;
			this.runtimeOptionsEntry.InvisibleChar = '•';
			this.table1.Add (this.runtimeOptionsEntry);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.runtimeOptionsEntry]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.showClrExcCheck = new global::Gtk.CheckButton ();
			this.showClrExcCheck.CanFocus = true;
			this.showClrExcCheck.Name = "showClrExcCheck";
			this.showClrExcCheck.Label = global::Mono.Unix.Catalog.GetString ("Show CLR exceptions");
			this.showClrExcCheck.DrawIndicator = true;
			this.showClrExcCheck.UseUnderline = true;
			this.table1.Add (this.showClrExcCheck);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.showClrExcCheck]));
			w8.TopAttach = ((uint)(4));
			w8.BottomAttach = ((uint)(5));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.showExcDetailCheck = new global::Gtk.CheckButton ();
			this.showExcDetailCheck.CanFocus = true;
			this.showExcDetailCheck.Name = "showExcDetailCheck";
			this.showExcDetailCheck.Label = global::Mono.Unix.Catalog.GetString ("Show exception details");
			this.showExcDetailCheck.DrawIndicator = true;
			this.showExcDetailCheck.UseUnderline = true;
			this.table1.Add (this.showExcDetailCheck);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.showExcDetailCheck]));
			w9.TopAttach = ((uint)(5));
			w9.BottomAttach = ((uint)(6));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.versionComboBox = global::Gtk.ComboBox.NewText ();
			this.versionComboBox.Name = "versionComboBox";
			this.table1.Add (this.versionComboBox);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.versionComboBox]));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.warnInconsistentTabCheck = new global::Gtk.CheckButton ();
			this.warnInconsistentTabCheck.CanFocus = true;
			this.warnInconsistentTabCheck.Name = "warnInconsistentTabCheck";
			this.warnInconsistentTabCheck.Label = global::Mono.Unix.Catalog.GetString ("Warn inconsistent tabbing");
			this.warnInconsistentTabCheck.DrawIndicator = true;
			this.warnInconsistentTabCheck.UseUnderline = true;
			this.table1.Add (this.warnInconsistentTabCheck);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.warnInconsistentTabCheck]));
			w11.TopAttach = ((uint)(6));
			w11.BottomAttach = ((uint)(7));
			w11.RightAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			this.alignment1.Add (this.table1);
			this.vbox1.Add (this.alignment1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.alignment1]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
